# Header
menu:
  ä¸»é¡µ: /
  æ–‡ç« : /archives
  å…³äº: /about

# SubNav
subnav:
  github: "https://github.com/m2shad0w"
  weibo: "http://weibo.com/712310784"
  rss: "#"
  # zhihu: "http://www.zhihu.com/people/M2shad0w"
  # douban: "http://www.douban.com/people/m2shad0w"
  mail: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "https://twitter.com/m2shad0w"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# æ˜¯å¦å¼€å¯åŠ¨ç”»æ•ˆæœ
animate: true

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# Miscellaneous
google_analytics: 'UA-66782235-1'
favicon: http://7xk4vd.com1.z0.glb.clouddn.com/faviconwhite-letter-m-centered-inside-black-circle-hi.png
# ä½ çš„å¤´åƒurl
avatar: http://7xk4vd.com1.z0.glb.clouddn.com/my.jpg
# æ˜¯å¦å¼€å¯åˆ†äº«
share: true
# æ˜¯å¦å¼€å¯å¤šè¯´è¯„è®ºï¼Œå¡«å†™ä½ åœ¨å¤šè¯´ç”³è¯·çš„é¡¹ç›®åç§° duoshuo: duoshuo-key
# è‹¥ä½¿ç”¨disqusï¼Œè¯·åœ¨åšå®¢configæ–‡ä»¶ä¸­å¡«å†™disqus_shortnameï¼Œå¹¶å…³é—­å¤šè¯´è¯„è®º
# duoshuo: true
# æ˜¯å¦å¼€å¯äº‘æ ‡ç­¾
tagcloud: true

# æ˜¯å¦å¼€å¯å‹æƒ…é“¾æ¥
# ä¸å¼€å¯â€”â€”
# friends: false
# å¼€å¯â€”â€”
friends:
  matt: http://tang3w.com/
  onevcat: http://onevcat.com/
  èµµçš„å°çª: http://zhaojin97.cn/
  Fenng:  http://dbanotes.net/
# æ˜¯å¦å¼€å¯â€œå…³äºæˆ‘â€ã€‚
# ä¸å¼€å¯â€”â€”
# aboutme: false
# å¼€å¯â€”â€”
aboutme: é£ç¿”çš„ğŸ
